"""update_transcript_model

Revision ID: 0b87cccd01d4
Revises: 310a9ac0bfae
Create Date: 2026-07-09 21:35:24.680057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b87cccd01d4'
down_revision: Union[str, Sequence[str], None] = '310a9ac0bfae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_transcripts', sa.Column('role', sa.String(), server_default='user', nullable=False))
    op.drop_column('call_transcripts', 'seq')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_transcripts', sa.Column('seq', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('call_transcripts', 'role')
    # ### end Alembic commands ###
