"""Recover original status

Revision ID: 953626b4966b
Revises: 
Create Date: 2026-06-23 17:01:59.027573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '953626b4966b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_emotion_analyses', 'status')
    op.drop_column('hospitals', 'build_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('build_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('ai_emotion_analyses', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
