"""update-call-sid-nullable

Revision ID: a194a3cd5830
Revises: d7dcf2b90f9a
Create Date: 2026-06-29 11:59:10.074004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a194a3cd5830'
down_revision: Union[str, Sequence[str], None] = 'd7dcf2b90f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_emotion_analyses', sa.Column('model_used', sa.String(), nullable=False))
    op.add_column('calls', sa.Column('provider_sid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'provider_sid')
    op.drop_column('ai_emotion_analyses', 'model_used')
    # ### end Alembic commands ###
