"""update-create-at

Revision ID: d7dcf2b90f9a
Revises: 953626b4966b
Create Date: 2026-06-26 11:39:32.772532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7dcf2b90f9a'
down_revision: Union[str, Sequence[str], None] = '953626b4966b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_dispatch_recommendations', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('ai_dispatch_recommendations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('ai_emotion_analyses', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('ai_emotion_analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('ai_triage_assessments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('ai_triage_assessments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('call_transcripts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('call_transcripts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('calls', sa.Column('caller_name', sa.String(), nullable=True))
    op.add_column('calls', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('calls', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('calls', 'transcript')
    op.add_column('dispatcher_actions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('dispatcher_actions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('dispatchers', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('dispatchers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('dispatches', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('dispatches', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('hospital_capacity', 'updated_at')
    op.add_column('hospitals', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('hospitals', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('incident_logs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('incident_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('incidents', sa.Column('coordinates', postgresql.ARRAY(sa.Float()), nullable=True))
    op.add_column('incidents', sa.Column('title', sa.String(), nullable=False))
    op.add_column('incidents', sa.Column('location', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('ai_confidence', sa.Float(), nullable=True))
    op.add_column('incidents', sa.Column('ai_summary', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('incidents', 'type',
               existing_type=postgresql.ENUM('medical', 'fire', 'crime', 'accident', 'flood', name='incidenttype'),
               nullable=True)
    op.alter_column('incidents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('response_units', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('response_units', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('response_units', 'last_updated')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response_units', sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('response_units', 'updated_at')
    op.drop_column('response_units', 'created_at')
    op.alter_column('incidents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('incidents', 'type',
               existing_type=postgresql.ENUM('medical', 'fire', 'crime', 'accident', 'flood', name='incidenttype'),
               nullable=False)
    op.drop_column('incidents', 'updated_at')
    op.drop_column('incidents', 'ai_summary')
    op.drop_column('incidents', 'ai_confidence')
    op.drop_column('incidents', 'location')
    op.drop_column('incidents', 'title')
    op.drop_column('incidents', 'coordinates')
    op.alter_column('incident_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('incident_logs', 'updated_at')
    op.drop_column('hospitals', 'updated_at')
    op.drop_column('hospitals', 'created_at')
    op.add_column('hospital_capacity', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('dispatches', 'updated_at')
    op.drop_column('dispatches', 'created_at')
    op.drop_column('dispatchers', 'updated_at')
    op.drop_column('dispatchers', 'created_at')
    op.alter_column('dispatcher_actions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('dispatcher_actions', 'updated_at')
    op.add_column('calls', sa.Column('transcript', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('calls', 'updated_at')
    op.drop_column('calls', 'created_at')
    op.drop_column('calls', 'caller_name')
    op.drop_column('call_transcripts', 'updated_at')
    op.drop_column('call_transcripts', 'created_at')
    op.alter_column('ai_triage_assessments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('ai_triage_assessments', 'updated_at')
    op.alter_column('ai_emotion_analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('ai_emotion_analyses', 'updated_at')
    op.alter_column('ai_dispatch_recommendations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('ai_dispatch_recommendations', 'updated_at')
    # ### end Alembic commands ###
