"""frontend-er-diagram

Revision ID: e32452956aa3
Revises: a194a3cd5830
Create Date: 2026-06-30 17:43:55.462925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e32452956aa3'
down_revision: Union[str, Sequence[str], None] = 'a194a3cd5830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_emotion_analyses', sa.Column('start_duration', sa.Float(), nullable=False))
    op.add_column('ai_emotion_analyses', sa.Column('end_duration', sa.Float(), nullable=False))
    op.add_column('incidents', sa.Column('severity', sa.Enum('CRITICAL', 'URGENT', 'MODERATE', 'RESOLVED', name='severitytype'), nullable=True))
    op.add_column('incidents', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('incidents', sa.Column('occur_date_time', sa.DateTime(), nullable=True))
    op.add_column('incidents', sa.Column('distress_score', sa.Float(), nullable=True))
    op.add_column('incidents', sa.Column('panic_level', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('entities', sa.JSON(), nullable=True))
    op.add_column('incidents', sa.Column('reason', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('contradiction', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('sop_citation', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('sop_procedure', sa.JSON(), nullable=True))
    op.add_column('incidents', sa.Column('responder', sa.JSON(), nullable=True))
    op.add_column('incidents', sa.Column('timeline', sa.JSON(), nullable=True))
    op.add_column('incidents', sa.Column('transcript', sa.JSON(), nullable=True))
    op.add_column('incidents', sa.Column('status', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'status')
    op.drop_column('incidents', 'transcript')
    op.drop_column('incidents', 'timeline')
    op.drop_column('incidents', 'responder')
    op.drop_column('incidents', 'sop_procedure')
    op.drop_column('incidents', 'sop_citation')
    op.drop_column('incidents', 'contradiction')
    op.drop_column('incidents', 'reason')
    op.drop_column('incidents', 'entities')
    op.drop_column('incidents', 'panic_level')
    op.drop_column('incidents', 'distress_score')
    op.drop_column('incidents', 'occur_date_time')
    op.drop_column('incidents', 'priority')
    op.drop_column('incidents', 'severity')
    op.drop_column('ai_emotion_analyses', 'end_duration')
    op.drop_column('ai_emotion_analyses', 'start_duration')
    # ### end Alembic commands ###
